<?php

namespace Tests\Browser;

use App\DelegateRole;
use App\Event;
use App\Ticket;
use App\User;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Laravel\Dusk\Browser;
use Tests\DuskTestCase;

class AdminCreateDelegateTest extends DuskTestCase
{
    use DatabaseMigrations;

    private $admin;
    private $event;

    protected function setUp() {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->admin = factory(User::class)->create();
        $this->event = factory(Event::class)->create();
        factory(DelegateRole::class)->create();
        factory(Ticket::class)->create();

        $this->actingAs($this->admin);
    }

    /**
     * A Dusk test example.
     *
     * @return void
     */
    public function testExample() {
        $this->browse(function (Browser $browser) {
            $browser->visit('/events/' . $this->event->id . '/delegates/create')
                    ->type('prefix', 'Mr')
                    ->type('is_male', '1')
                    ->type('last_name', 'Au')
                    ->type('first_name', 'Xavier')
                    ->type('address_1', 'address 1')
                    ->type('address_2', 'address 2')
                    ->type('email', 'xavier.au@gmail.com')
                    ->type('mobile', '66218556')
                    ->type('address_3', 'address 3')
                    ->type('department', 'IT')
                    ->type('ticket_id', '1')
                    ->select('roles_id[]', '1')
                    ->press('Submit')
                    ->assertPathIs('/events/' . $this->event->id . '/delegates');
        });
    }
}
