<?php

namespace Tests\Feature;

use App\Event;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class NotificationControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @var \App\Event
     */
    private $event;

    protected function setUp() {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->event = factory(Event::class)->create();
    }

    /**
     * @test
     */
    public function get_create_page() {

        $this->withoutExceptionHandling();

        $this->singIn();

        $uri = route('events.notifications.create', $this->event);
        $response = $this->get($uri);
        $response->assertSuccessful();

    }
}
