<?php

namespace Tests\Feature;

use App\Event;
use App\User;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;

class ShowTicketIndexPageTest extends TestCase
{
    use DatabaseMigrations;

    private $admin;
    private $event;

    protected function setUp() {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->admin = factory(User::class)->create();
        $this->event = factory(Event::class)->create();

        $this->actingAs($this->admin);
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function test() {
        $response = $this->get('/events/' . $this->event->id . '/tickets');

        $response->assertSee("Tickets for Event: " . $this->event->name);
    }
}
